// Autogenerated from Pigeon (v3.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, PermissionStatus) {
  PermissionStatusGranted = 0,
  PermissionStatusDenied = 1,
};

typedef NS_ENUM(NSUInteger, PermissionType) {
  PermissionTypeActivityRecognition = 0,
  PermissionTypeOAuth = 1,
};

@class PermissionResult;
@class HealthConnectData;
@class HealthConnectWorkoutData;

@interface PermissionResult : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPermissionType:(PermissionType)permissionType
    permissionStatus:(PermissionStatus)permissionStatus;
@property(nonatomic, assign) PermissionType permissionType;
@property(nonatomic, assign) PermissionStatus permissionStatus;
@end

@interface HealthConnectData : NSObject
+ (instancetype)makeWithWeight:(nullable NSNumber *)weight
    height:(nullable NSNumber *)height;
@property(nonatomic, strong, nullable) NSNumber * weight;
@property(nonatomic, strong, nullable) NSNumber * height;
@end

@interface HealthConnectWorkoutData : NSObject
+ (instancetype)makeWithUuid:(nullable NSString *)uuid
    identifier:(nullable NSString *)identifier
    name:(nullable NSString *)name
    description:(nullable NSString *)description
    activity:(nullable NSString *)activity
    startTimestamp:(nullable NSNumber *)startTimestamp
    endTimestamp:(nullable NSNumber *)endTimestamp
    duration:(nullable NSNumber *)duration;
@property(nonatomic, copy, nullable) NSString * uuid;
@property(nonatomic, copy, nullable) NSString * identifier;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, copy, nullable) NSString * description;
@property(nonatomic, copy, nullable) NSString * activity;
@property(nonatomic, strong, nullable) NSNumber * startTimestamp;
@property(nonatomic, strong, nullable) NSNumber * endTimestamp;
@property(nonatomic, strong, nullable) NSNumber * duration;
@end

/// The codec used by HealthConnectHostApi.
NSObject<FlutterMessageCodec> *HealthConnectHostApiGetCodec(void);

@protocol HealthConnectHostApi
- (void)requestActivityRecognitionPermissionWithCompletion:(void(^)(PermissionResult *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)hasActivityRecognitionPermissionWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)requestOAuthPermissionWithCompletion:(void(^)(PermissionResult *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)hasOAuthPermissionWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)openSettingsWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)disconnectWithCompletion:(void(^)(FlutterError *_Nullable))completion;
- (void)getHealthConnectDataWithCompletion:(void(^)(HealthConnectData *_Nullable, FlutterError *_Nullable))completion;
- (void)getHealthConnectWorkoutsDataWithCompletion:(void(^)(NSArray<HealthConnectWorkoutData *> *_Nullable, FlutterError *_Nullable))completion;
- (void)subscribeToHealthConnectWorkoutsDataWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void HealthConnectHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HealthConnectHostApi> *_Nullable api);

/// The codec used by HealthConnectFlutterApi.
NSObject<FlutterMessageCodec> *HealthConnectFlutterApiGetCodec(void);

@interface HealthConnectFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onWorkoutDataUpdatedHealthConnectWorkoutData:(HealthConnectWorkoutData *)healthConnectWorkoutData completion:(void(^)(NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
